### ISSUE TITLE
Collision problem with my .ncp file

### ISSUE THREAD

**Issue by ghost** [Dummiesman/HabitatB#20]
Hey,
I'm making a track with Blender and for some reason when i export my track some edges or faces behave strange as if there was a hole or something. When i look at the .ncp file in Blender i don't see anything bad, all is solid and there is no hole between the different faces. The problem appears very few times but it's very annoying, it makes the track unplayable. Maybe i do something wrong.
Here is a picture of my problem, you can see that the car falls a little as if there was no floor at this place :
http://www.cjoint.com/doc/17_10/GJzjaGnyRdZ_revolt.jpg

**Comment by Yethiel** [comment]
You have to triangulate non-planar faces (CTRL T) but it might also be a bug in the NCP export.
I've since been working on a new add-on, you can find it here: https://yethiel.github.io/re-volt-addon/

**Comment by ghost** [comment]
I tested my track during 5 minutes with the new add-on and it seems to work fine.
Thanks Yethiel for your (fast) answer.
